### ISSUE TITLE
Could u give me compiled version for me?  :)

### ISSUE THREAD

**Issue by dlwowns22** [jpxue/Overwatch-Aim-Assist#11]
Sorry for requesting, but I don't know how compiled this.

plz compile it for Korean OW (its title name is 오버워치)
humanlike = true
head = false

send email to pro__jc@naver.com 

thanks for see this :)

**Comment by Yakultie** [comment]
Emailed you.

**Comment by dlwowns22** [comment]
Could u send me 

aim : body
human like

title "Overwatch" too??

when it(ver.kor) doesn't working, i want to use it(ver.eng)

-----Original Message-----

**Comment by Yakultie** [comment]
I replied to your email. If you want to do it yourself, you can download Visual Studio from Microsoft, then import the C++ files.
