### ISSUE TITLE
could you teach me how to compile it?

### ISSUE THREAD

**Issue by uijin55** [jpxue/Overwatch-Aim-Assist#12]
I'm a newbie in vb things, but i know it's perfect program for my ow life..

but i don't know how to compile it , there is no project file? to open it, many cpp, h files there

plz tell me how to compile it and apply it to ow in detail..

thanks for all.. (even i install vb 2015 from website only for this)

**Comment by jpxue** [comment]
Sure, it's not complicated at all as there are no dependencies and you do not need to mess around with the linker; should take you 2 minutes. 

New Project -> Visual C++ -> Empty Project 
You will see a folder names 'Source Files' and 'Header Files' just drag and drop the .cpp files in source files and the .h files in header files. 

If you get a warning about using the old C Runtime libraries (which you likely will):
Right click on the solution -> Properties -> C/C++ -> Preprocessor -> Preprocessor Definitions -> Add '_CRT_SECURE_NO_WARNINGS'. {Do this for both Debug and Release}

Build -> Run in Release Mode
