### ISSUE TITLE
Issue with aim assist.

### ISSUE THREAD

**Issue by The-Whargoul** [jpxue/Overwatch-Aim-Assist#14]
Hello, So I can't seem to get the aim assist to work, triggerbot works just fine. 
I was hoping to find a way to resolve this on my own, so I can learn. However I simply have no clue where to begin.

you've already done more than enough by sharing this with us, however if you could point me in the right direction, I'd be grateful

**Comment by jpxue** [comment]
Hmmm, what's happening? Is the crosshair not moving at all?

**Comment by The-Whargoul** [comment]
No, the cross hair does not move at all. However I haven't tinkered with it
since. I saw another thread having a similar issue where you advised them
to add breakpoints on given lines within one of the header files. So I
decided to try that, but those breakpoints were never hit.

**Comment by jpxue** [comment]
I can recall another person having this problem who solved it by replacing lines 70-71 in capture.cpp:

int sWidth = GetSystemMetrics(SM_CXSCREEN);
int sHeight = GetSystemMetrics(SM_CYSCREEN);

Replace these lines with your actual resolution i.e. if your resolution is 1920x1080 they should be:

int sWidth = 1920;
int sHeight = 1080;

Do you get any errors in the command prompt itself?
