### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by tonyshin12** [jpxue/Overwatch-Aim-Assist#16]

**Comment by tonyshin12** [comment]
so I was building this, I used vc++ 2015, and it says something about stdafx.h blah blah and to 
include stdafx.h. anyone knows howw to help?

**Comment by jpxue** [comment]
https://github.com/jpxue/Overwatch-Aim-Assist/issues/12

**Comment by tonyshin12** [comment]
I THINK IT DOESNT WORK NOW... 
i COMPILED IT AND IT STARTED BUT IT DOESN'T WORK
LET ME SHOW YOU THE VIDEO https://youtu.be/Z7hdDWzHLlw

**Comment by tonyshin12** [comment]
AND WHAT IS TRIGGERBOT??

**Comment by jpxue** [comment]
Could be that the RGB values for the health bar are different in your PC
thus it is not being detected or else:
https://github.com/jpxue/Overwatch-Aim-Assist/issues

**Comment by jpxue** [comment]
Can you take a screenshot (with fraps or something) with the health bar
showing so that I can confirm the RGB values in the healthbar.

**Comment by tonyshin12** [comment]
![default](https://cloud.githubusercontent.com/assets/10667507/19428167/5e85dd02-9483-11e6-9c48-24c8b5983624.PNG)

**Comment by tonyshin12** [comment]
I'm using a notebook!!

**Comment by tonyshin12** [comment]
what do you think is the matter?? the rgb value is right, but the aim goes to the floor
