### ISSUE TITLE
localtime

### ISSUE THREAD

**Issue by Foxfire9** [jpxue/Overwatch-Aim-Assist#17]
Hi man I have issues using localtime it gives c4996 error dunno why
![error2](https://cloud.githubusercontent.com/assets/23010201/19625180/1eefbe18-9944-11e6-847f-f72bf95a9026.png)
![error1](https://cloud.githubusercontent.com/assets/23010201/19625181/1ef1942c-9944-11e6-9aad-b1adc3f9a695.png)

**Comment by Foxfire9** [comment]
Is it okay to disable it ?

**Comment by jpxue** [comment]
http://lmgtfy.com/?q=_crt_secure_no_warnings+visual+studio+2015
