### ISSUE TITLE
issue with aim assist

### ISSUE THREAD

**Issue by tonyshin12** [jpxue/Overwatch-Aim-Assist#18]
![default](https://cloud.githubusercontent.com/assets/10667507/20344441/1f79aba0-ac36-11e6-8bad-aa4a49b3b433.png)
I have a very big issue with aim assist
so, if the aim has to go to the yellow  circle, it goes to the red one... 
how can i solve this

**Comment by KIDJourney** [comment]
Nice painting.

**Comment by tonyshin12** [comment]
no one knows how to solve this??

**Comment by xiaofen9** [comment]
Try this project https://github.com/xiaofen9/overwatch
