### ISSUE TITLE
mouse_event() get detected and screenshots are blocked!

### ISSUE THREAD

**Issue by Sh4d0wBlade** [jpxue/Overwatch-Aim-Assist#27]
HI jpxue,are you still working on it?Now They(you konw who i refer to-:)) DO DETECT the mouse messages or events,but this is not trivial(we have baskets of methods of mouse simulation),the importance is that they also anti SCREENSHOTS!!! so the DC/Bitmap functions may not work...So I use GetPixel,buf this function is TOOOOO SLOW...so,Any better idea???

**Comment by Sh4d0wBlade** [comment]
oh by the way i also have tried the "DXGI desktop duplication sample" which is provided by microsoft and it is open source,then it works in capturing the screen.but after i perused the codes in obtaining the frames of my screen,only to find that i can't gain pixel information from the frame buffer(actually, i do not know how to obtain pixels from the buffer.the buffer is a ID3D11Texture2D structure buffer.you can find ID3D11Texture2D in msdn).So if you have any good idea please inform me.

**Comment by Sh4d0wBlade** [comment]
and,i have learned the display port driver and WDDM on msdn(you do not want to know how hard it is, a long haul actually),after all of this, i feel that i got fucked...

**Comment by mickaelreil** [comment]
Hey, you just have to use OBS Studio.

**Comment by Sh4d0wBlade** [comment]
I have never heard of this OBS before,or thought of launching overwatch in screen recorder softwares...I will check it out.happy chinese new year(in overwatch)!

**Comment by mickaelreil** [comment]
Thank you to you too. You'll just have to replace the WidowName value.

**Comment by massi1234567** [comment]
@mickaelreil somehow when i use obs it just aims for the ground? Any idea why?
