### ISSUE TITLE
Mouse not moving to the enemy

### ISSUE THREAD

**Issue by Owfanboy** [jpxue/Overwatch-Aim-Assist#4]
The mouse not moving to the enemy's head/body at all. It just keep moving to the lower right corner whenever the Hp bar is presented. I tried with both borderless 1920x1080 and 1280x720. With different mouse sen but still not work. Seems like it calculated the coordination of the enemy's head/body wrong.

**Comment by jpxue** [comment]
Does this occur in the training range or in an actual game?
Also, does it occur when you set Headshots to false?

**Comment by Owfanboy** [comment]
-Happens in the practice range
-Doesn't matter headshot and humanizer is on or off, it just keep aiming to the bottom right of the enemy.

**Comment by jpxue** [comment]
For me to get an idea why this happens I need to now some more info, you can do this by running the application in debug mode and setting debug points in lines 241 and 253 as shown below (to create debug points just click to the left of the line number and you will see a red circle):

http://imgur.com/a/4qYyh

**Comment by Owfanboy** [comment]
Fixed. Have to manually put the screen resolution into Mouse.cpp
