### ISSUE TITLE
Hello I really like your code

### ISSUE THREAD

**Issue by mosesyumss** [jpxue/Overwatch-Aim-Assist#5]
but I think it is slow...

**Comment by jpxue** [comment]
It's a colour aimbot thus there are limitations (compared to other types of aimbots) but thank you :)
On my computer it runs great but I cannot make something that is optimized to run all machines.

It takes ~40ms to take a screenshot using the windows API (that cannot really improved much unless I obtain the pixels using the d3d backbuffer) but the main algorithm only takes me 8ms which is pretty fast in my opinion (in release mode).
This is all on an Intel core i7 920 with an Nvidia 960GTX. 
What are your computer specifications if you don't mind me asking?

**Comment by mosesyumss** [comment]
My computer is not good I just used it with my laptop..
I think it will be nice if it doesn't have uneccesary steps. and just directly aim at the target.

**Comment by jpxue** [comment]
There are not extra steps (everything is pretty much mandatory) but it does need optimization for slower hardware yes.

**Comment by spoofjack** [comment]
Threading?

**Comment by jpxue** [comment]
^ Most certainly, but also I need to improved mouse movements. I noticed that it takes the algorithm 3 detections/3 mouse movements to more or less get to the desired coordinates. I've been told how I can calculate this and there are public sources online but I do not want to rip off someone's algorithm

**Comment by w88975** [comment]
@jpxue I feel you are Chinese 😬

**Comment by spoofjack** [comment]
@w88975 What does that have to do with anything?
