### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by ghost** [jpxue/Overwatch-Aim-Assist#7]
I don't have the same application as you in your video, I use visual studio 2012 and I don't have the "x64" option.
When I attempt to attach, my overwatch crashes
When I attempt to debug, the program "unable to be found" and "doesn't exist"

**Comment by ghost** [comment]
Error I got on Visual Studio 2015 trying to release/debug into x64 is LNK1561 "entry point must be defined"

**Comment by jpxue** [comment]
The linker is simply not finding the main function in Program.cpp even though it should be there.
You can try setting the Subsytem field in Configuration Properties -> Linker -> System to "/SUBSYSTEM:CONSOLE".

If it does not work I'd recommend starting a new Empty Project, drag and drop the .cpp files in the Source Files folder and the .h files in the Header Files folder (although I'm assuming that this is what you did).
